---
- name: Create the config directory
  file:
    path: "/etc/hopglass-server/{{ hopglass_site }}"
    state: directory
    owner: hopglass
    group: hopglass

- name: Configure the server
  copy:
    src: "{{ hopglass_config_file }}"
    dest: "/etc/hopglass-server/{{ hopglass_site }}/config.json"
    owner: hopglass
    group: hopglass

- name: Configure the aliases
  copy:
    src: "{{ hopglass_aliases_file }}"
    dest: "/etc/hopglass-server/{{ hopglass_site }}/aliases.json"
    owner: hopglass
    group: hopglass
  when: hopglass_aliases_file is defined

- name: Install the hopglass service
  template:
    src: hopglass-server@.service
    dest: /lib/systemd/system/hopglass-server@.service
  notify: Reload systemd

- name: Enable and start the service for the site
  systemd:
    name: "hopglass-server@{{ hopglass_site }}"
    state: started
    enabled: true

- name: Configure the sysctl parameters for hopglass
  sysctl:
    name: "{{ item[0] }}"
    value: "{{ item[1] }}"
  with_dict:
  - { name: "net.core.rmem_default", value: 4194304 }
  - { name: "net.core.wmem_default", value: 4194304 }
  - { name: "net.core.rmem_max", value: 16777216 }
  - { name: "net.core.wmem_max", value: 16777216 }
