---
- name: Setup the hopglass user
  user:
    name: 'hopglass'
    comment: 'User for the hopglass server'
    home: "{{ hopglass_home }}"
    state: present

- name: Clone the hopglass server Repository
  git:
    repo: https://github.com/hopglass/hopglass-server.git
    dest: "{{ hopglass_home }}/hopglass-server"
    version: v0.1.3
    force: yes

- name: Install the hopglass server dependencies
  npm:
    path: "{{ hopglass_home }}/hopglass-server"
    state: latest
  become_user: hopglass
